"""views/tutorial.py — Installation Tutorial page."""

import streamlit as st


def render() -> None:
    st.markdown('<h1 style="margin-bottom:0.4rem">Installation Tutorial</h1>', unsafe_allow_html=True)
    st.caption("Complete guide to install and configure Personal Toolkit · Techco.lab on a new machine.")

    st.info("**Source code:** [github.com/keok-netzsch/techcolab-backlog](https://github.com/keok-netzsch/techcolab-backlog)", icon="📦")

    st.markdown("""
## Prerequisites

| Tool | Minimum version | Download |
|---|---|---|
| Python | 3.12 | python.org/downloads |
| Ollama | Any recent | ollama.com/download |
| Obsidian | Any recent | obsidian.md |
| Git | Any recent | git-scm.com |

> **Tip:** When installing Python on Windows, check the **"Add Python to PATH"** option before clicking Install Now.

---

## Installation

### Step 1 — Clone the repository

```bat
git clone https://github.com/keok-netzsch/techcolab-backlog.git
cd techcolab-backlog
```

### Step 2 — Install dependencies

**Option A — Automatic script (recommended)**

Double-click **`install.bat`** in the project folder.

**Option B — Manual**

```bat
python -m venv .venv
.venv\\Scripts\\activate
pip install -r requirements.txt
```

---

## Configuration

Open **`config.py`** and set `VAULT_ROOT` to your Obsidian vault path:

```python
VAULT_ROOT = r"C:\\Users\\YourUser\\Documents\\MyVault"
```

Or set the environment variable `TECHCOLAB_VAULT` (takes precedence over `config.py`):

```bat
set TECHCOLAB_VAULT=C:\\Users\\YourUser\\Documents\\MyVault
```

**How to find the path:** Obsidian → Settings → About → Vault path.

> Use `r"..."` before the quotes (raw string) to avoid issues with backslashes on Windows.

---

## Ollama model download

```bat
ollama pull llama3.2:3b
```

Download ~2 GB. To verify: `ollama list` — the model should appear in the list.

---

## Starting the app

- **Easiest:** double-click **`start_app.bat`**
- **Command line:**
  ```bat
  .venv\\Scripts\\activate
  streamlit run app.py
  ```
- Access at: **http://localhost:8501**

---

## Using the app

The app has a **top navigation bar** with the logo on the left and page links across the top. Click any link to navigate. The 🔄 icon on the far right refreshes all data from disk.

| Page | Purpose |
|---|---|
| Dashboard | Home — metrics overview, status/priority breakdown, to-dos due this week |
| Backlog | Create, edit and view ideas (list or kanban view) |
| To-Do List | All action items consolidated across all ideas, sortable and filterable |
| Team | Direct reports — 1:1 tracker, OKR / PDI status, and Ollama agenda generation |
| Claude Pro | HTML adoption report + Token Coach calculator |
| Weekly Brief | Preparation panel for meetings with leadership |
| English Coach | Progress tracker for AI-evaluated English practice sessions |
| 📖 (Tutorial) | This page |
| 📚 (Documentation) | Technical architecture and planned phases |

**Status flow:**
```
backlog → under review → approved → waiting → in development → in validation → done ✅
                       └─► rejected / discarded ⛔
```

### Priority badges

In the Backlog list view and To-Do List, priority is shown as a numbered circle:

| Badge | Priority |
|---|---|
| ● 3 (dark) | Alta / High |
| ● 2 (medium) | Média / Medium |
| ● 1 (light) | Baixa / Low |

### To-do states

Each to-do supports three states, toggled via the selectbox (To-Do List) or the state dropdown (Backlog card):

| Symbol | Meaning |
|---|---|
| ⬜ | Open — not started |
| 🔄 | In progress — started but not done |
| ✅ | Done — completed (records `completed_at` date) |

### Agent authorisation per to-do

The 🤖 checkbox on each to-do marks it as pre-approved for the daily agent.
Pre-approved to-dos appear with `[x]` already checked in the agent report — no manual approval needed.
You can set this during to-do creation or by editing the idea card later.

### Weekly Brief

Open **Weekly Brief** before any meeting with Alberto Reuters or Stefan Lautenschlager.

- Use the period slider (default 7 days) to set the reporting window
- Toggle sections on/off with the checkboxes
- Download the summary as `.md` for pasting into emails or Obsidian notes
- The **Calls** section auto-populates from session notes generated by the call recorder
- **Call com Gestor** (Win+Space → option 3) records calls with Alberto Reuters or Stefan Lautenschlager; notes are saved to `Stakeholders/{Name}/1on1/`

---

## Raycast shortcuts

All daily interactions are available directly via keyboard — no terminal needed.
Scripts live in `%USERPROFILE%\\techcolab-backlog\\call-recorder\\` and are registered in Raycast → Settings → Script Commands.

| Shortcut | Command | What it does |
|---|---|---|
| ⊞ Win + Space | **Call Recorder** | Opens menu: 1on1 com time / English Coach / Call com Gestor |
| ⊞ Win + C | **Encerrar Sessão** | Runs tests, commits and pushes the repo |
| *(assign)* | **Rodar Agente** | Runs Phase 1 — generates today's backlog report |
| *(assign)* | **Executar Agente** | Copies Phase 2 command to clipboard + opens Claude Code |

> **To assign a hotkey:** Raycast → Settings → Script Commands → click "Record Hotkey" next to the command.
> **To add or change scripts:** edit the `.ps1` files in the `call-recorder` folder — Raycast picks them up automatically (click "Reload Script Commands" if needed).

### Executar Agente — how it works

When you trigger **Executar Agente**:
1. The exact command is copied to your clipboard automatically
2. A terminal opens showing the report path
3. Claude Code launches in the project directory
4. Press **Ctrl+V** then **Enter** — done

No need to remember or type anything.

---

## Daily agent

The agent runs every morning at 08:00, analyses the backlog, and proposes actions.
You interact with it in two steps:

### Step 1 — Review the report (Obsidian)

Open the file `Backlog - to do - app/agent-reports/report-YYYY-MM-DD.md` in Obsidian.

The **Proposed actions** section lists specific to-dos from your backlog, grouped by idea:

```
**`idea-004`** ⭐⭐⭐ _Análise de agentes_ — Backlog, effort: ?
- [ ] Criar um fluxo de ideias

**`idea-008`** ⭐⭐⭐ _Planejamento OKR FY27_ — Backlog, effort: médio
- [ ] Pensar em áreas de melhoria (due 2026-05-29)
- [ ] Incluir item sobre adesão de AI no time
```

Check the boxes (`- [x]`) next to every to-do you want the agent to implement.
Leave unchecked what you don't approve — the agent will not touch those.

### Step 2 — Execute approved items (Claude Code)

**Easiest way — Raycast:**
Trigger **Executar Agente** (assign a hotkey in Raycast → Script Commands).
The command is copied to clipboard automatically — just paste in Claude Code and press Enter.

**Manual way:**
1. Double-click **`execute_agent.bat`** in the project folder
2. A terminal opens showing today's report path — press any key
3. Claude Code opens in the project directory
4. Type (or paste) exactly:

```
Execute the approved items from today's agent report
```

5. Claude reads the report, lists the approved to-dos, and asks you to confirm
6. After confirmation, Claude implements each to-do, runs the tests, and commits

> **Tip:** You can be more specific — e.g. *"Execute only the first two approved items"*
> or *"Skip idea-008, execute the rest."*

---

## Troubleshooting

| Issue | Solution |
|---|---|
| Connection error when suggesting to-dos | Start Ollama (tray icon) |
| App shows stale data | Click **🔄** in the top navigation bar (far right) |
| Port 8501 in use | `streamlit run app.py --server.port 8502` |
| "python not recognized" | Reinstall Python with "Add to PATH" checked |
| pip install error | Activate `.venv` first: `.venv\\Scripts\\activate` |
| Agent report not found | Run `run_agent.bat` manually to generate it |
| `TECHCOLAB_VAULT` error in app | Restart the app — the env var is set but needs a new process |

---

## Claude Pro Report

The **Claude Pro** page is a native Streamlit page that tracks Claude Pro usage and adoption metrics for the NBS D&A team.

Data is driven by two JSON files in `reports/`:
- `claude-pro-data.json` — initiatives, tools and executive summary (edit manually or via agent)
- `claude-pro-timeline.json` — chronological activity log (auto-updated by the daily agent)

There is no external HTML file or GitHub Pages dependency — the page renders live from the JSON on every load.

### What gets updated automatically

Every morning when the daily agent runs, it:

| Action | Target |
|---|---|
| Adds today's git commits as a timeline entry | `claude-pro-timeline.json` |
| Backfills any missing session dates (last 7 days) from JSONL scraping | `claude-pro-timeline.json` |
| Patches live backlog stats (total items, open bugs) into the toolkit initiative | `claude-pro-data.json` |

The page also auto-refreshes the timeline once on first load each day. To force an immediate refresh at any time, use the **🔄 Refresh** button in the top-right of the Claude Pro page.
""")
